### ISSUE TITLE
Cop idea: `first(...)` instead of `all(...)[0]`

### ISSUE THREAD

**Issue by ydah** [rubocop/rubocop-capybara#115]
https://www.rubydoc.info/gems/capybara/Capybara%2FNode%2FFinders:first

```ruby
# bad
all('td')[0]

# good
first('td')
```

**Comment by boris-petrov** [comment]
I just came to open an issue about that. :smile: 

By the way, another case that could be replaced with `first` is `find(..., match: :first)`. @ydah do you want me to open a new issue about that or you'll handle it here?

**Comment by ydah** [comment]
@boris-petrov Supported by https://github.com/rubocop/rubocop-capybara/pull/118 . If this is not a problem, I will merge it.

**Comment by boris-petrov** [comment]
Seems great! Thanks for the quick implementation as usual! :)

**Comment by timdiggins** [comment]
@ydah is the main motivation for this stylistic ? Or does the `.all` not do the same waiting that `.first` does?

I'm going to try to write up a justification for this in https://github.com/rubocop/capybara-style-guide if I have time. 

PS in the ideal world - there would be an addition to the style guide in the form of a PR or issues at the same time as the cop issue is raised... Perhaps we could add that suggestion to the Issue template?

**Comment by ydah** [comment]
@timdiggins Sorry for the delay in replying, I am ready for https://github.com/rubocop/capybara-style-guide and would be happy to have you write. This cop is motivated by stylistic.
