### ISSUE TITLE
official manual is not found

### ISSUE THREAD

**Issue by tricknotes** [rubocop/rubocop-capybara#15]
The official manual that documented in README shows "Page Not Found".
https://github.com/rubocop/rubocop-capybara/blob/ff1f5469c9cc35b207f5de6b413163dbfda55021/README.md#L64

https://docs.rubocop.org/rubocop-capybara
<img width="1343" alt="screenshot" src="https://user-images.githubusercontent.com/290782/210825995-5676db75-93cb-4731-99d0-9302892c1621.png">

**Comment by tricknotes** [comment]
Thanks for letting me know.
I'm looking forward to publishing a new release.

**Comment by koic** [comment]
https://docs.rubocop.org/rubocop-capybara/2.17/index.html has been published.

**Comment by ydah** [comment]
@koic Thank you!
