### ISSUE TITLE
Autocorrect for expect(current_path) moves method argument when parens are absent

### ISSUE THREAD

**Issue by DanielHeath** [rubocop/rubocop-capybara#37]
Code like `expect(page.current_path).to eq(article_path article)` gets autocorrected to 

`expect(page).to have_current_path(article_path article, ignore_query: true)`
The correct form is 
`expect(page).to have_current_path article_path(article, ignore_query: true)`

**Comment by ydah** [comment]
Thank you for your feedback! You're absolutely right, so I have opened https://github.com/rubocop/rubocop-capybara/pull/39
