### ISSUE TITLE
Misunderstanding with Capybara/NegationMatcher

### ISSUE THREAD

**Issue by ydakuka** [rubocop/rubocop-capybara#57]
## Actual behavior

The default behavior of the `rubocop-capybara` is inconsistent with the rspec style guide.

Reference 1: https://rspec.rubystyle.guide/#capybara-negative-selectors
Reference 2: https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaranegationmatcher

## Expected behavior

The rspec style guide will be corrected.

**Comment by mvz** [comment]
@ydah how up-to-date is the rspec style guide really? That rule may stem from a time when `not_to have..` would not invoke Capybara's timeout logic.

**Comment by pirj** [comment]
@mvz it might be significantly outdated. I maintain it, but I’m not an expert in Capybara, so most of Capybara-related guidelines are inherited from older guides. I appreciate if you could contribute and update the guide.

**Comment by ydah** [comment]
Maybe we should extract factory_bot and capybara guidelines from rspec-style-guide?

**Comment by pirj** [comment]
There are not enough guidelines for Capybara/FB now. But if someone is up to create such a guide, I’d be happy to move existing guidelines there.
