### ISSUE TITLE
[Capybara/SpecificMatcher] False-positive when using regex

### ISSUE THREAD

**Issue by boris-petrov** [rubocop/rubocop-capybara#82]
```rb
expect(page).to have_css('button', exact_text: /my regex+/)
```

This should not trigger the `Capybara/SpecificMatcher` because there is no way to write this with `have_button`. Same applies for `text` with regex in addition to `exact_text`.

**Comment by svegaca** [comment]
It also has false-positive issues in expectations that include CSS class names. It seems that `have_field`, `have_link`, and `have_button` don't currently support the `class` option.

**Comment by boris-petrov** [comment]
@svegaca - hm, I have to following in my tests:

```rb
expect(page).to have_button(class: 'btn-close')
```

Are you saying that this doesn't work? It seems to pass. :smile:

**Comment by svegaca** [comment]
Yes, it fails for me using `capybara (2.4.4)` and `rubocop-capybara (2.17.0)`. Maybe I should upgrade capybara 😅 but looking at the current code I don't find where it accepts the `class` option 🤔

**Comment by boris-petrov** [comment]
Well, it passes `options` to `has_selector?` which does work with `class:` so it should be fine. :)
